const defaultContest = {
	formal_name: "UMNPC Internal Contest 2026",
	scoreboard_type: "scoring",
	start_time: "2026-04-30T11:00:00+00:00",
	end_time: "2026-05-04T11:30:00+00:00",
	scoreboard_thaw_time: "2026-05-04T11:30:00+00:00",
	duration: "96:30:00.000",
	scoreboard_freeze_duration: "0:00:00.000",
	cid: 6,
	id: "IC2026",
	name: "UMNPC Internal Contest 2026",
	shortname: "IC26",
	allow_submit: true,
	runtime_as_score_tiebreaker: false,
	warning_message: null,
	penalty_time: 30,
};

const defaultScoreboard = {
	event_id: "1080",
	time: "2026-04-29T13:36:56.191+00:00",
	contest_time: "-21:23:03.809",
	state: {
		started: null,
		ended: null,
		frozen: null,
		thawed: null,
		finalized: null,
		end_of_updates: null,
	},
	rows: [
		{
			rank: 1,
			team_id: "dj-6",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
		{
			rank: 1,
			team_id: "dj-12",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
		{
			rank: 1,
			team_id: "dj-16",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
		{
			rank: 1,
			team_id: "dj-15",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
		{
			rank: 1,
			team_id: "dj-9",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
		{
			rank: 1,
			team_id: "dj-11",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
		{
			rank: 1,
			team_id: "dj-14",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
		{
			rank: 1,
			team_id: "dj-7",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
		{
			rank: 1,
			team_id: "dj-10",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
		{
			rank: 1,
			team_id: "dj-8",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
		{
			rank: 1,
			team_id: "dj-17",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
		{
			rank: 1,
			team_id: "dj-18",
			score: {
				num_solved: 0,
				total_time: 0,
			},
			problems: [
				{
					label: "Absolute Symmetry Encryption",
					problem_id: "AbsoluteSymmetryEncryption",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Battle Imbalance",
					problem_id: "BattleImbalance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Chain Reaction",
					problem_id: "ChainReaction",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Emergency Signal",
					problem_id: "EmergencySignal",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Generator Calibration",
					problem_id: "GeneratorCalibration",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
				{
					label: "Server Tolerance",
					problem_id: "ServerTolerance",
					num_judged: 0,
					num_pending: 0,
					solved: false,
					first_to_solve: false,
				},
			],
		},
	],
};

const defaultTeams = [
	{
		location: null,
		organization_id: null,
		hidden: true,
		group_ids: ["system"],
		affiliation: null,
		nationality: null,
		photo: [
			{
				href: "contests/IC2026/teams/domjudge/photo",
				mime: "image/jpeg",
				filename: "photo.jpg",
				width: 320,
				height: 200,
			},
		],
		teamid: 1,
		id: "domjudge",
		icpc_id: null,
		label: "domjudge",
		name: "DOMjudge",
		display_name: null,
		public_description: null,
	},
	{
		location: null,
		organization_id: null,
		hidden: true,
		group_ids: ["system"],
		affiliation: null,
		nationality: null,
		teamid: 3,
		id: "dj-3",
		icpc_id: null,
		label: "dj-3",
		name: "jury",
		display_name: "jury",
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-3",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Sistem Informasi",
		nationality: "IDN",
		teamid: 6,
		id: "dj-6",
		icpc_id: "Assiqque",
		label: "dj-6",
		name: "Assiqque",
		display_name: null,
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-4",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Informatika",
		nationality: "IDN",
		teamid: 7,
		id: "dj-7",
		icpc_id: null,
		label: "dj-7",
		name: "Pejuang++",
		display_name: "Pejuang++",
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-4",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Informatika",
		nationality: "IDN",
		teamid: 8,
		id: "dj-8",
		icpc_id: "izinserius",
		label: "dj-8",
		name: "izinserius",
		display_name: null,
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-4",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Informatika",
		nationality: "IDN",
		teamid: 9,
		id: "dj-9",
		icpc_id: null,
		label: "dj-9",
		name: "Gege",
		display_name: null,
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-5",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Managemen",
		nationality: "IDN",
		teamid: 10,
		id: "dj-10",
		icpc_id: "Squad",
		label: "dj-10",
		name: "Squad",
		display_name: "Squad",
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-5",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Managemen",
		nationality: "IDN",
		teamid: 11,
		id: "dj-11",
		icpc_id: null,
		label: "dj-11",
		name: "LUA",
		display_name: "LUA",
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-5",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Managemen",
		nationality: "IDN",
		teamid: 12,
		id: "dj-12",
		icpc_id: null,
		label: "dj-12",
		name: "BIndo",
		display_name: "BIndo",
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-4",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Informatika",
		nationality: "IDN",
		teamid: 14,
		id: "dj-14",
		icpc_id: null,
		label: "dj-14",
		name: "Mambo mamboo... Hachiiimiiii",
		display_name: "Mambo mamboo... Hachiiimiiii",
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-4",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Informatika",
		nationality: "IDN",
		teamid: 15,
		id: "dj-15",
		icpc_id: null,
		label: "dj-15",
		name: "GaPunyaNama",
		display_name: "GaPunyaNama",
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-4",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Informatika",
		nationality: "IDN",
		teamid: 16,
		id: "dj-16",
		icpc_id: null,
		label: "dj-16",
		name: "CTRL + V",
		display_name: "CTRL + V",
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-4",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Informatika",
		nationality: "IDN",
		teamid: 17,
		id: "dj-17",
		icpc_id: null,
		label: "dj-17",
		name: "Kemaren habis diajarin competitive programming sama claude opus, hari ini insyaallah menang",
		display_name: "nama tim yang panjang itu",
		public_description: null,
	},
	{
		location: null,
		organization_id: "dj-3",
		hidden: false,
		group_ids: ["participants"],
		affiliation: "Sistem Informasi",
		nationality: "IDN",
		teamid: 18,
		id: "dj-18",
		icpc_id: null,
		label: "dj-18",
		name: "nyengir pro max",
		display_name: "nyengir pro max",
		public_description: null,
	},
];

const defaultProblems = [
	{
		ordinal: 0,
		probid: 12,
		short_name: "Absolute Symmetry Encryption",
		rgb: null,
		color: null,
		label: "Absolute Symmetry Encryption",
		time_limit: 1,
		statement: [
			{
				href: "contests/IC2026/problems/AbsoluteSymmetryEncryption/statement",
				mime: "application/pdf",
				filename: "Absolute Symmetry Encryption.pdf",
			},
		],
		attachments: [],
		id: "AbsoluteSymmetryEncryption",
		name: "Absolute Symmetry Encryption",
		test_data_count: 20,
	},
	{
		ordinal: 1,
		probid: 14,
		short_name: "Battle Imbalance",
		rgb: null,
		color: null,
		label: "Battle Imbalance",
		time_limit: 1,
		statement: [
			{
				href: "contests/IC2026/problems/BattleImbalance/statement",
				mime: "application/pdf",
				filename: "Battle Imbalance.pdf",
			},
		],
		attachments: [],
		id: "BattleImbalance",
		name: "Battle Imbalance",
		test_data_count: 20,
	},
	{
		ordinal: 2,
		probid: 16,
		short_name: "Chain Reaction",
		rgb: null,
		color: null,
		label: "Chain Reaction",
		time_limit: 1,
		statement: [
			{
				href: "contests/IC2026/problems/ChainReaction/statement",
				mime: "application/pdf",
				filename: "Chain Reaction.pdf",
			},
		],
		attachments: [],
		id: "ChainReaction",
		name: "Chain Reaction",
		test_data_count: 20,
	},
	{
		ordinal: 3,
		probid: 11,
		short_name: "Emergency Signal",
		rgb: null,
		color: null,
		label: "Emergency Signal",
		time_limit: 1,
		statement: [
			{
				href: "contests/IC2026/problems/EmergencySignal/statement",
				mime: "application/pdf",
				filename: "Emergency Signal.pdf",
			},
		],
		attachments: [],
		id: "EmergencySignal",
		name: "Emergency Signal",
		test_data_count: 20,
	},
	{
		ordinal: 4,
		probid: 13,
		short_name: "Generator Calibration",
		rgb: null,
		color: null,
		label: "Generator Calibration",
		time_limit: 1,
		statement: [
			{
				href: "contests/IC2026/problems/GeneratorCalibration/statement",
				mime: "application/pdf",
				filename: "Generator Calibration.pdf",
			},
		],
		attachments: [],
		id: "GeneratorCalibration",
		name: "Generator Calibration",
		test_data_count: 15,
	},
	{
		ordinal: 5,
		probid: 17,
		short_name: "Server Tolerance",
		rgb: null,
		color: null,
		label: "Server Tolerance",
		time_limit: 1,
		statement: [
			{
				href: "contests/IC2026/problems/ServerTolerance/statement",
				mime: "application/pdf",
				filename: "Server Tolerance.pdf",
			},
		],
		attachments: [],
		id: "ServerTolerance",
		name: "Server Tolerance",
		test_data_count: 20,
	},
];

export { defaultContest, defaultScoreboard, defaultTeams, defaultProblems };
